version: '3'
services:
  discordbot:
    build: .
    container_name: discord-bot
    volumes:
      - ./data:/app/data  # Montre le dossier local 'data' dans le conteneur
    environment:
      - DISCORD_TOKEN=<Your_Token>  # Remplace par ton token
    restart: unless-stopped
